"""pessoa 2 com idade

Revision ID: d2c11800d3c5
Revises: 6a725d99bfe8
Create Date: 2022-07-20 10:39:47.778471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c11800d3c5'
down_revision = '6a725d99bfe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa2', sa.Column('idades', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa2', 'idades')
    # ### end Alembic commands ###
